export type Region = 'popular' | 'europe' | 'asia' | 'americas' | 'africa' | 'oceania';

export interface RegionCity {
  id: string;   // Teleport slug
  city: string;
}

const REGION_CITIES: Record<Exclude<Region, 'popular'>, RegionCity[]> = {
  europe: [
    { id: 'amsterdam',       city: 'Amsterdam'       },
    { id: 'athens',          city: 'Athens'          },
    { id: 'barcelona',       city: 'Barcelona'       },
    { id: 'berlin',          city: 'Berlin'          },
    { id: 'birmingham',      city: 'Birmingham'      },
    { id: 'brussels',        city: 'Brussels'        },
    { id: 'bucharest',       city: 'Bucharest'       },
    { id: 'budapest',        city: 'Budapest'        },
    { id: 'cologne',         city: 'Cologne'         },
    { id: 'copenhagen',      city: 'Copenhagen'      },
    { id: 'dublin',          city: 'Dublin'          },
    { id: 'edinburgh',       city: 'Edinburgh'       },
    { id: 'frankfurt',       city: 'Frankfurt'       },
    { id: 'hamburg',         city: 'Hamburg'         },
    { id: 'helsinki',        city: 'Helsinki'        },
    { id: 'istanbul',        city: 'Istanbul'        },
    { id: 'lisbon',          city: 'Lisbon'          },
    { id: 'london',          city: 'London'          },
    { id: 'lyon',            city: 'Lyon'            },
    { id: 'madrid',          city: 'Madrid'          },
    { id: 'manchester',      city: 'Manchester'      },
    { id: 'milan',           city: 'Milan'           },
    { id: 'moscow',          city: 'Moscow'          },
    { id: 'munich',          city: 'Munich'          },
    { id: 'oslo',            city: 'Oslo'            },
    { id: 'paris',           city: 'Paris'           },
    { id: 'prague',          city: 'Prague'          },
    { id: 'rome',            city: 'Rome'            },
    { id: 'stockholm',       city: 'Stockholm'       },
    { id: 'toulouse',        city: 'Toulouse'        },
    { id: 'valencia',        city: 'Valencia'        },
    { id: 'vienna',          city: 'Vienna'          },
    { id: 'warsaw',          city: 'Warsaw'          },
    { id: 'zurich',          city: 'Zurich'          },
  ],
  asia: [
    { id: 'abu-dhabi',       city: 'Abu Dhabi'       },
    { id: 'bangkok',         city: 'Bangkok'         },
    { id: 'beijing',         city: 'Beijing'         },
    { id: 'chennai',         city: 'Chennai'         },
    { id: 'chengdu',         city: 'Chengdu'         },
    { id: 'delhi',           city: 'Delhi'           },
    { id: 'dhaka',           city: 'Dhaka'           },
    { id: 'dubai',           city: 'Dubai'           },
    { id: 'guangzhou',       city: 'Guangzhou'       },
    { id: 'ho-chi-minh-city',city: 'Ho Chi Minh City'},
    { id: 'hong-kong',       city: 'Hong Kong'       },
    { id: 'hyderabad',       city: 'Hyderabad'       },
    { id: 'jakarta',         city: 'Jakarta'         },
    { id: 'karachi',         city: 'Karachi'         },
    { id: 'kolkata',         city: 'Kolkata'         },
    { id: 'kuala-lumpur',    city: 'Kuala Lumpur'    },
    { id: 'kyoto',           city: 'Kyoto'           },
    { id: 'lahore',          city: 'Lahore'          },
    { id: 'manila',          city: 'Manila'          },
    { id: 'mumbai',          city: 'Mumbai'          },
    { id: 'osaka',           city: 'Osaka'           },
    { id: 'riyadh',          city: 'Riyadh'          },
    { id: 'seoul',           city: 'Seoul'           },
    { id: 'shanghai',        city: 'Shanghai'        },
    { id: 'shenzhen',        city: 'Shenzhen'        },
    { id: 'singapore',       city: 'Singapore'       },
    { id: 'taipei',          city: 'Taipei'          },
    { id: 'tehran',          city: 'Tehran'          },
    { id: 'tokyo',           city: 'Tokyo'           },
  ],
  americas: [
    { id: 'atlanta',         city: 'Atlanta'         },
    { id: 'austin',          city: 'Austin'          },
    { id: 'bogota',          city: 'Bogotá'          },
    { id: 'boston',          city: 'Boston'          },
    { id: 'buenos-aires',    city: 'Buenos Aires'    },
    { id: 'calgary',         city: 'Calgary'         },
    { id: 'chicago',         city: 'Chicago'         },
    { id: 'dallas',          city: 'Dallas'          },
    { id: 'denver',          city: 'Denver'          },
    { id: 'guadalajara',     city: 'Guadalajara'     },
    { id: 'houston',         city: 'Houston'         },
    { id: 'lima',            city: 'Lima'            },
    { id: 'los-angeles',     city: 'Los Angeles'     },
    { id: 'medellin',        city: 'Medellín'        },
    { id: 'mexico-city',     city: 'Mexico City'     },
    { id: 'miami',           city: 'Miami'           },
    { id: 'minneapolis',     city: 'Minneapolis'     },
    { id: 'montreal',        city: 'Montreal'        },
    { id: 'new-york',        city: 'New York'        },
    { id: 'philadelphia',    city: 'Philadelphia'    },
    { id: 'portland',        city: 'Portland'        },
    { id: 'rio-de-janeiro',  city: 'Rio de Janeiro'  },
    { id: 'san-diego',       city: 'San Diego'       },
    { id: 'san-francisco',   city: 'San Francisco'   },
    { id: 'santiago',        city: 'Santiago'        },
    { id: 'sao-paulo',       city: 'São Paulo'       },
    { id: 'seattle',         city: 'Seattle'         },
    { id: 'toronto',         city: 'Toronto'         },
    { id: 'vancouver',       city: 'Vancouver'       },
    { id: 'washington-dc',   city: 'Washington D.C.' },
  ],
  africa: [
    { id: 'accra',           city: 'Accra'           },
    { id: 'addis-ababa',     city: 'Addis Ababa'     },
    { id: 'cairo',           city: 'Cairo'           },
    { id: 'cape-town',       city: 'Cape Town'       },
    { id: 'casablanca',      city: 'Casablanca'      },
    { id: 'dar-es-salaam',   city: 'Dar es Salaam'   },
    { id: 'johannesburg',    city: 'Johannesburg'    },
    { id: 'kampala',         city: 'Kampala'         },
    { id: 'khartoum',        city: 'Khartoum'        },
    { id: 'lagos',           city: 'Lagos'           },
    { id: 'nairobi',         city: 'Nairobi'         },
    { id: 'tunis',           city: 'Tunis'           },
  ],
  oceania: [
    { id: 'adelaide',        city: 'Adelaide'        },
    { id: 'auckland',        city: 'Auckland'        },
    { id: 'brisbane',        city: 'Brisbane'        },
    { id: 'canberra',        city: 'Canberra'        },
    { id: 'christchurch',    city: 'Christchurch'    },
    { id: 'gold-coast',      city: 'Gold Coast'      },
    { id: 'melbourne',       city: 'Melbourne'       },
    { id: 'perth',           city: 'Perth'           },
    { id: 'queenstown',      city: 'Queenstown'      },
    { id: 'sydney',          city: 'Sydney'          },
    { id: 'wellington',      city: 'Wellington'      },
  ],
};

export function useTeleportRegionCities(region: Region): {
  cities: RegionCity[];
  loading: boolean;
  error: string | null;
} {
  if (region === 'popular') {
    return { cities: [], loading: false, error: null };
  }
  return { cities: REGION_CITIES[region], loading: false, error: null };
}
